In [64]:
import torch

In [65]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [66]:
a[1]

tensor(1.)

In [67]:
float(a[1])

1.0

In [68]:
int(a[1])

1

In [69]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [70]:
points = torch.zeros(6)
points

tensor([0., 0., 0., 0., 0., 0.])

In [71]:
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [72]:
#we can also pass a python list

points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [73]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [74]:
# 2D tensors

points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [75]:
print(points.shape)

print(points[0])

print(points[1,0])

torch.Size([3, 2])
tensor([4., 1.])
tensor(5.)


In [76]:
zeros = torch.zeros(3,2)

once = torch.ones(4,3)

print(zeros.shape, once.shape)

torch.Size([3, 2]) torch.Size([4, 3])


### Indexing tensors

In [77]:
# points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [78]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [79]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [80]:
points[1:, 0]

tensor([5., 2.])

In [81]:
# added a dimention of size 1
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [82]:
# same can be done by this function
points.unsqueeze(dim=0)

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

### Broadcasting

In [83]:
values = torch.tensor([[1,2,3]])
values

tensor([[1, 2, 3]])

In [84]:
added_value = values + 10
print(added_value)

tensor([[11, 12, 13]])


In [87]:
multiple_value = values * torch.tensor([[10],[20],[30]])
multiple_value

tensor([[10, 20, 30],
        [20, 40, 60],
        [30, 60, 90]])

In [89]:
torch.tensor([[1,2,3],[4,5,6]]) + torch.tensor([[[10,20,30]],[[40,50,60]]])

tensor([[[11, 22, 33],
         [14, 25, 36]],

        [[41, 52, 63],
         [44, 55, 66]]])

### Named tensors

In [94]:
img_t = torch.randn(3,5,5) # channels, rows, columns
weights  = torch.tensor([0.2126, 0.7152, 0.0722])

img_t, img_t.shape

(tensor([[[ 0.2206,  0.0547, -1.9510,  0.1768, -1.2641],
          [ 0.0572,  1.9768, -0.1280,  0.7296,  0.3284],
          [-1.5255,  1.1158, -1.0132,  0.2625, -1.3331],
          [-0.3666,  2.3410,  1.0735,  1.2012, -0.3017],
          [ 2.2250, -0.0762,  1.2698, -0.7024, -0.0652]],
 
         [[ 0.3924, -0.4674, -0.6152, -1.1572,  0.0721],
          [ 0.6144, -0.0558,  0.5239, -1.7811, -0.9081],
          [-0.3894, -0.0522, -1.3488,  0.7899, -0.0670],
          [-0.4470,  0.1749,  2.5242, -0.9908,  0.2972],
          [ 0.0802,  0.6872, -0.2943,  0.2557, -2.9033]],
 
         [[ 1.0831, -1.5142, -0.2965, -0.1901,  0.5939],
          [-0.2985, -1.1830,  1.0726, -1.4417, -1.3397],
          [ 0.1162, -0.0090,  0.4896,  0.3911, -0.6546],
          [-0.8725, -1.7516,  1.5420,  1.1841, -0.6089],
          [-0.3336,  1.1748,  0.9991, -0.2926, -0.0494]]]),
 torch.Size([3, 5, 5]))

In [96]:
batch = torch.randn(2,3,5,5) # batch, channels, rows, columns
batch

tensor([[[[-1.1609,  0.8270,  0.8038, -0.7004, -1.0099],
          [ 0.2911, -0.6513, -1.8265,  1.4486,  0.8653],
          [-0.5959,  0.1040, -2.0313,  2.1127,  1.1035],
          [-0.2875,  1.5298,  0.4836,  0.0316, -1.2457],
          [-0.5274,  1.2368, -0.0069, -0.5823, -1.6673]],

         [[ 0.4999, -0.3111,  0.8210,  3.5421, -0.4559],
          [ 0.5501, -0.1069,  0.1576,  0.2104, -1.5031],
          [ 2.1994,  0.9931, -1.0031,  0.7575, -0.7409],
          [ 1.3231,  1.5755, -0.0466, -0.4303, -1.6445],
          [-1.2880,  0.8364,  0.4649,  1.8363,  0.7750]],

         [[ 1.6806,  2.1729,  0.5015,  0.1302,  1.4099],
          [-1.2771, -0.3238, -0.1686, -0.1997,  0.5830],
          [ 0.6973, -0.3712,  0.0062,  0.0916,  0.7921],
          [-0.0972,  0.8702,  0.3427,  0.2762, -0.2987],
          [ 0.4569, -0.1535, -0.6605,  0.8765, -0.5920]]],


        [[[-0.5800,  0.1127, -0.8387, -0.2214,  0.0730],
          [ 0.1380,  1.4852, -0.6417,  0.4267,  0.1960],
          [-0.8548,  0.

In [97]:
img_gray_native = img_t.mean(-3)
batch_gray_native = batch.mean(-3)

img_gray_native.shape, batch_gray_native.shape


(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [99]:
weights

tensor([0.2126, 0.7152, 0.0722])

In [98]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [100]:
img_weight = img_t * unsqueezed_weights
img_weight


tensor([[[ 4.6903e-02,  1.1623e-02, -4.1479e-01,  3.7597e-02, -2.6875e-01],
         [ 1.2154e-02,  4.2026e-01, -2.7208e-02,  1.5511e-01,  6.9823e-02],
         [-3.2433e-01,  2.3721e-01, -2.1541e-01,  5.5815e-02, -2.8342e-01],
         [-7.7944e-02,  4.9769e-01,  2.2822e-01,  2.5538e-01, -6.4141e-02],
         [ 4.7302e-01, -1.6196e-02,  2.6995e-01, -1.4934e-01, -1.3856e-02]],

        [[ 2.8066e-01, -3.3431e-01, -4.3996e-01, -8.2761e-01,  5.1548e-02],
         [ 4.3942e-01, -3.9939e-02,  3.7472e-01, -1.2739e+00, -6.4949e-01],
         [-2.7851e-01, -3.7331e-02, -9.6463e-01,  5.6491e-01, -4.7896e-02],
         [-3.1969e-01,  1.2512e-01,  1.8053e+00, -7.0864e-01,  2.1259e-01],
         [ 5.7378e-02,  4.9147e-01, -2.1045e-01,  1.8286e-01, -2.0764e+00]],

        [[ 7.8199e-02, -1.0933e-01, -2.1407e-02, -1.3724e-02,  4.2882e-02],
         [-2.1549e-02, -8.5411e-02,  7.7440e-02, -1.0409e-01, -9.6728e-02],
         [ 8.3901e-03, -6.5197e-04,  3.5348e-02,  2.8241e-02, -4.7262e-02],
        

In [101]:
batch_weight = batch * unsqueezed_weights
batch_weight

tensor([[[[-2.4680e-01,  1.7582e-01,  1.7090e-01, -1.4889e-01, -2.1471e-01],
          [ 6.1890e-02, -1.3847e-01, -3.8830e-01,  3.0798e-01,  1.8397e-01],
          [-1.2669e-01,  2.2115e-02, -4.3185e-01,  4.4916e-01,  2.3461e-01],
          [-6.1127e-02,  3.2523e-01,  1.0282e-01,  6.7102e-03, -2.6483e-01],
          [-1.1213e-01,  2.6293e-01, -1.4696e-03, -1.2379e-01, -3.5448e-01]],

         [[ 3.5756e-01, -2.2250e-01,  5.8715e-01,  2.5333e+00, -3.2607e-01],
          [ 3.9342e-01, -7.6466e-02,  1.1273e-01,  1.5047e-01, -1.0750e+00],
          [ 1.5730e+00,  7.1026e-01, -7.1745e-01,  5.4179e-01, -5.2987e-01],
          [ 9.4630e-01,  1.1268e+00, -3.3340e-02, -3.0772e-01, -1.1761e+00],
          [-9.2118e-01,  5.9820e-01,  3.3253e-01,  1.3133e+00,  5.5428e-01]],

         [[ 1.2134e-01,  1.5688e-01,  3.6209e-02,  9.3969e-03,  1.0180e-01],
          [-9.2207e-02, -2.3379e-02, -1.2171e-02, -1.4418e-02,  4.2093e-02],
          [ 5.0343e-02, -2.6804e-02,  4.4887e-04,  6.6149e-03,  5.7187e-

In [102]:
img_gray_weighted = img_weight.sum(-3)
batch_gray_weighted = batch_weight.sum(-3)

batch_weight.shape, batch.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))