In [1]:
import torch

In [2]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
a[1]

tensor(1.)

In [4]:
float(a[1])

1.0

In [5]:
int(a[1])

1

In [6]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [7]:
points = torch.zeros(6)
points

tensor([0., 0., 0., 0., 0., 0.])

In [8]:
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
#we can also pass a python list

points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [10]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [11]:
# 2D tensors

points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
print(points.shape)

print(points[0])

print(points[1,0])

torch.Size([3, 2])
tensor([4., 1.])
tensor(5.)


In [13]:
zeros = torch.zeros(3,2)

once = torch.ones(4,3)

print(zeros.shape, once.shape)

torch.Size([3, 2]) torch.Size([4, 3])


### Indexing tensors

In [14]:
# points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [16]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [17]:
points[1:, 0]

tensor([5., 2.])

In [18]:
# added a dimention of size 1
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [19]:
# same can be done by this function
points.unsqueeze(dim=0)

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

### Broadcasting

In [20]:
values = torch.tensor([[1,2,3]])
values

tensor([[1, 2, 3]])

In [21]:
added_value = values + 10
print(added_value)

tensor([[11, 12, 13]])


In [22]:
multiple_value = values * torch.tensor([[10],[20],[30]])
multiple_value

tensor([[10, 20, 30],
        [20, 40, 60],
        [30, 60, 90]])

In [23]:
torch.tensor([[1,2,3],[4,5,6]]) + torch.tensor([[[10,20,30]],[[40,50,60]]])

tensor([[[11, 22, 33],
         [14, 25, 36]],

        [[41, 52, 63],
         [44, 55, 66]]])

### Named tensors

In [24]:
img_t = torch.randn(3,5,5) # channels, rows, columns
weights  = torch.tensor([0.2126, 0.7152, 0.0722])

img_t, img_t.shape

(tensor([[[-0.4366, -2.5213,  1.2765, -1.0245,  0.6430],
          [-0.7378,  0.4784, -0.2220, -1.5520, -0.9303],
          [-1.3727,  1.5295, -0.8790,  0.3542,  0.9226],
          [ 0.5721,  0.6868,  0.1534, -1.1668,  0.3272],
          [-0.3464, -0.1910,  0.5841,  0.1901, -0.7649]],
 
         [[-1.4164,  0.3840,  0.3616, -0.0799,  1.2115],
          [ 1.0823,  0.5545, -0.6644,  0.4236,  0.2369],
          [ 1.4617,  2.0280,  0.3182, -0.1031, -0.1306],
          [ 0.3735,  0.9945,  0.1264,  0.4037, -0.4094],
          [ 0.7175, -0.2020, -0.1282, -0.7085,  0.0308]],
 
         [[-1.5798, -1.2226, -0.2295, -1.1131,  0.3183],
          [-0.2341,  1.7776, -1.5758, -1.1364, -2.0007],
          [ 0.6160, -0.5963, -0.6541,  0.5647,  0.6533],
          [-1.4258, -0.2287, -0.7687,  0.2416,  1.0313],
          [-0.3026,  0.0258, -0.0219, -0.3382, -0.3531]]]),
 torch.Size([3, 5, 5]))

In [25]:
batch = torch.randn(2,3,5,5) # batch, channels, rows, columns
batch

tensor([[[[-0.4059, -0.4934, -0.3377, -0.1431, -0.2746],
          [-0.2374, -1.3753, -0.8799, -2.2889,  0.4215],
          [-0.1856, -1.0563, -1.1042,  1.4427, -0.3387],
          [ 0.9777,  2.0416,  0.8378,  0.1908,  0.6866],
          [-0.5839,  0.1741,  1.7783,  1.7055, -0.8121]],

         [[-1.0698,  1.0154,  1.5101, -1.1105, -0.0187],
          [ 1.1368, -0.5593, -0.5426,  0.3459,  1.9803],
          [-0.3448,  0.5165, -0.8133,  2.0618, -0.8342],
          [ 0.2618,  0.1766,  1.5519,  0.8748, -1.9270],
          [-0.9962, -0.4153,  0.1453, -0.6330, -0.7260]],

         [[-2.0052, -0.3320,  0.0737,  0.3354, -0.2911],
          [-0.1789,  0.9129,  1.2317,  0.6491,  0.6850],
          [ 1.3335, -0.8408,  1.6971, -0.3396, -0.3408],
          [ 1.3964,  0.6845, -0.3567, -0.0918, -0.7298],
          [-0.5787,  1.3127, -1.2473,  0.2738,  1.4174]]],


        [[[ 2.2419, -0.7353,  0.6431, -0.2604, -0.9268],
          [ 2.3177, -1.0750, -0.3321,  0.8753, -0.6202],
          [-0.8153,  0.

In [26]:
img_gray_native = img_t.mean(-3)
batch_gray_native = batch.mean(-3)

img_gray_native.shape, batch_gray_native.shape


(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [27]:
weights

tensor([0.2126, 0.7152, 0.0722])

In [28]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [29]:
img_weight = img_t * unsqueezed_weights
img_weight


tensor([[[-0.0928, -0.5360,  0.2714, -0.2178,  0.1367],
         [-0.1569,  0.1017, -0.0472, -0.3300, -0.1978],
         [-0.2918,  0.3252, -0.1869,  0.0753,  0.1961],
         [ 0.1216,  0.1460,  0.0326, -0.2481,  0.0696],
         [-0.0736, -0.0406,  0.1242,  0.0404, -0.1626]],

        [[-1.0130,  0.2746,  0.2586, -0.0571,  0.8665],
         [ 0.7741,  0.3966, -0.4752,  0.3030,  0.1695],
         [ 1.0454,  1.4504,  0.2275, -0.0738, -0.0934],
         [ 0.2671,  0.7112,  0.0904,  0.2887, -0.2928],
         [ 0.5132, -0.1445, -0.0917, -0.5067,  0.0221]],

        [[-0.1141, -0.0883, -0.0166, -0.0804,  0.0230],
         [-0.0169,  0.1283, -0.1138, -0.0820, -0.1444],
         [ 0.0445, -0.0431, -0.0472,  0.0408,  0.0472],
         [-0.1029, -0.0165, -0.0555,  0.0174,  0.0745],
         [-0.0218,  0.0019, -0.0016, -0.0244, -0.0255]]])

In [30]:
batch_weight = batch * unsqueezed_weights
batch_weight

tensor([[[[-0.0863, -0.1049, -0.0718, -0.0304, -0.0584],
          [-0.0505, -0.2924, -0.1871, -0.4866,  0.0896],
          [-0.0395, -0.2246, -0.2348,  0.3067, -0.0720],
          [ 0.2079,  0.4341,  0.1781,  0.0406,  0.1460],
          [-0.1241,  0.0370,  0.3781,  0.3626, -0.1726]],

         [[-0.7651,  0.7262,  1.0801, -0.7943, -0.0134],
          [ 0.8130, -0.4000, -0.3881,  0.2474,  1.4163],
          [-0.2466,  0.3694, -0.5816,  1.4746, -0.5967],
          [ 0.1872,  0.1263,  1.1099,  0.6257, -1.3782],
          [-0.7125, -0.2970,  0.1039, -0.4527, -0.5192]],

         [[-0.1448, -0.0240,  0.0053,  0.0242, -0.0210],
          [-0.0129,  0.0659,  0.0889,  0.0469,  0.0495],
          [ 0.0963, -0.0607,  0.1225, -0.0245, -0.0246],
          [ 0.1008,  0.0494, -0.0258, -0.0066, -0.0527],
          [-0.0418,  0.0948, -0.0901,  0.0198,  0.1023]]],


        [[[ 0.4766, -0.1563,  0.1367, -0.0554, -0.1970],
          [ 0.4928, -0.2286, -0.0706,  0.1861, -0.1319],
          [-0.1733,  0.

In [31]:
img_gray_weighted = img_weight.sum(-3)
batch_gray_weighted = batch_weight.sum(-3)

batch_weight.shape, batch.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [32]:
# Named tensors allow aligning dimensions automatically by name using align_as
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch.refine_names(..., 'channels', 'rows', 'columns')
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=('channels',))

# align_as adds dimensions of size 1 and permutes dimensions to match the target tensor
weights_aligned = weights_named.align_as(img_named)
print("weights_aligned shape:", weights_aligned.shape, "names:", weights_aligned.names)

# Now broadcasting works cleanly across named dimensions
gray_named = (img_named * weights_aligned).sum('channels')
print("gray_named shape:", gray_named.shape, "names:", gray_named.names)


weights_aligned shape: torch.Size([3, 1, 1]) names: ('channels', 'rows', 'columns')
gray_named shape: torch.Size([5, 5]) names: ('rows', 'columns')


/media/tamal/New_HardDrive/Anaconda_Linux/envs/tamal/lib/python3.10/site-packages/torch/_tensor.py:1309: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at ../c10/core/TensorImpl.h:1928.)
  return super().refine_names(names)


### Managing a ternsor's dtype attribute

In [33]:
double_points = torch.ones(10, 2, dtype=torch.double)
double_points

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]], dtype=torch.float64)

In [34]:
double_points.dtype

torch.float64

In [35]:
# more convenient method:
double_points = torch.zeros(10,2).to(torch.double)
double_points.dtype

torch.float64

### The tensor API

In [36]:
# The transpose function can be used from the torch module as

a = torch.ones(3,2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

## Tensors: Scenic views of storage
### Indexing into storage
multiple tensors can index the same storage even if they index the data differently. A storage is one dimentional array

In [43]:
points = torch.tensor([[4,1],[5,3],[2,1]]).to(torch.float32)
print(points)
print("---------------------")
points.storage()

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])
---------------------


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [ ]:
# we can index into a storage manually

points_storage = points.storage()
print(points_storage[0])
points_storage[1]


4.0


1.0

### Modifying stored values: In place operations

In [ ]:
a = torch.ones(3,2)
a.zero_() # see the underscore, it converted all the previous input to zeros
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## Tensor metadata: Size, offset and stride