In [1]:
import torch

In [2]:
a = torch.ones(3)
a

tensor([1., 1., 1.])

In [3]:
a[1]

tensor(1.)

In [4]:
float(a[1])

1.0

In [5]:
int(a[1])

1

In [6]:
a[2] = 2.0
a

tensor([1., 1., 2.])

In [7]:
points = torch.zeros(6)
points

tensor([0., 0., 0., 0., 0., 0.])

In [8]:
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points

tensor([4., 1., 5., 3., 2., 1.])

In [9]:
#we can also pass a python list

points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [10]:
float(points[0]), float(points[1])

(4.0, 1.0)

In [11]:
# 2D tensors

points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [12]:
print(points.shape)

print(points[0])

print(points[1,0])

torch.Size([3, 2])
tensor([4., 1.])
tensor(5.)


In [13]:
zeros = torch.zeros(3,2)

once = torch.ones(4,3)

print(zeros.shape, once.shape)

torch.Size([3, 2]) torch.Size([4, 3])


### Indexing tensors

In [14]:
# points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [15]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [16]:
points[1:, :]

tensor([[5., 3.],
        [2., 1.]])

In [17]:
points[1:, 0]

tensor([5., 2.])

In [18]:
# added a dimention of size 1
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [19]:
# same can be done by this function
points.unsqueeze(dim=0)

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

### Broadcasting

In [20]:
values = torch.tensor([[1,2,3]])
values

tensor([[1, 2, 3]])

In [21]:
added_value = values + 10
print(added_value)

tensor([[11, 12, 13]])


In [22]:
multiple_value = values * torch.tensor([[10],[20],[30]])
multiple_value

tensor([[10, 20, 30],
        [20, 40, 60],
        [30, 60, 90]])

In [23]:
torch.tensor([[1,2,3],[4,5,6]]) + torch.tensor([[[10,20,30]],[[40,50,60]]])

tensor([[[11, 22, 33],
         [14, 25, 36]],

        [[41, 52, 63],
         [44, 55, 66]]])

### Named tensors

In [24]:
img_t = torch.randn(3,5,5) # channels, rows, columns
weights  = torch.tensor([0.2126, 0.7152, 0.0722])

img_t, img_t.shape

(tensor([[[-0.9460, -0.1229,  0.2936,  0.6556,  0.9606],
          [-0.5013,  0.2651, -1.2461, -0.8823,  0.9983],
          [ 1.1590,  0.8848,  1.3389, -0.3128, -0.3625],
          [-0.3764,  0.3559, -0.6145,  0.2274,  0.2508],
          [-0.4768, -0.2645,  1.6377, -0.0745,  0.7579]],
 
         [[ 0.4159,  0.6197, -0.5553,  0.3338, -1.7836],
          [ 1.3904,  0.0452,  0.4269, -1.2777,  0.7215],
          [ 1.2832, -1.7020, -1.0598, -1.9965,  1.7065],
          [-0.5583, -0.2973, -0.5978, -0.3583,  0.3506],
          [ 0.4110,  1.2043, -0.8245,  0.7773,  1.2703]],
 
         [[-0.5182, -0.9293,  0.1776, -0.4533, -0.1320],
          [ 2.4810, -0.1030, -0.7384, -1.3645,  0.0416],
          [-1.0560, -1.2608,  0.5945, -0.7395,  1.1626],
          [-0.3753, -0.7292,  1.3221, -0.7407, -0.3262],
          [ 0.6461, -0.4672,  1.2168,  1.3121,  0.3006]]]),
 torch.Size([3, 5, 5]))

In [25]:
batch = torch.randn(2,3,5,5) # batch, channels, rows, columns
batch

tensor([[[[ 0.0061, -1.1476, -0.5417,  0.2367,  0.0746],
          [-0.3218, -0.4650, -0.8127, -1.1052, -0.0697],
          [-0.3004,  0.7603,  0.3819,  2.0985, -0.2191],
          [-0.3855,  0.2872,  1.9078, -1.1673,  0.2991],
          [-0.0271, -0.6645,  1.1241, -0.0896,  0.0520]],

         [[-1.2873,  0.9867,  1.2469, -0.1489, -0.5197],
          [ 0.0962,  0.5913, -0.3690, -0.1289, -0.5590],
          [ 0.7625, -0.6792,  0.3695,  1.1517,  2.3860],
          [-0.3281,  0.9214, -0.1156,  1.0687, -0.8109],
          [-0.2095, -1.8874,  1.0213, -2.3871,  0.6787]],

         [[-0.2784,  0.1767,  1.8942, -0.0569, -1.3566],
          [-1.1904,  0.7950, -0.7525,  1.5212, -0.7169],
          [-1.3690,  0.7490,  1.0532, -0.8819, -0.3477],
          [-0.2629, -1.4476, -1.9932, -0.1639,  0.5669],
          [-0.4468,  1.3780, -0.6771, -1.0727,  0.3179]]],


        [[[-1.3752,  0.0998, -1.6188,  1.5030,  0.4309],
          [ 1.2568, -1.1019,  0.5837, -0.8228, -1.1433],
          [ 0.2086,  1.

In [26]:
img_gray_native = img_t.mean(-3)
batch_gray_native = batch.mean(-3)

img_gray_native.shape, batch_gray_native.shape


(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [27]:
weights

tensor([0.2126, 0.7152, 0.0722])

In [28]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [29]:
img_weight = img_t * unsqueezed_weights
img_weight


tensor([[[-0.2011, -0.0261,  0.0624,  0.1394,  0.2042],
         [-0.1066,  0.0564, -0.2649, -0.1876,  0.2122],
         [ 0.2464,  0.1881,  0.2847, -0.0665, -0.0771],
         [-0.0800,  0.0757, -0.1306,  0.0483,  0.0533],
         [-0.1014, -0.0562,  0.3482, -0.0158,  0.1611]],

        [[ 0.2975,  0.4432, -0.3972,  0.2387, -1.2756],
         [ 0.9944,  0.0323,  0.3054, -0.9138,  0.5160],
         [ 0.9177, -1.2173, -0.7580, -1.4279,  1.2205],
         [-0.3993, -0.2126, -0.4276, -0.2563,  0.2507],
         [ 0.2940,  0.8613, -0.5897,  0.5559,  0.9085]],

        [[-0.0374, -0.0671,  0.0128, -0.0327, -0.0095],
         [ 0.1791, -0.0074, -0.0533, -0.0985,  0.0030],
         [-0.0762, -0.0910,  0.0429, -0.0534,  0.0839],
         [-0.0271, -0.0526,  0.0955, -0.0535, -0.0235],
         [ 0.0466, -0.0337,  0.0879,  0.0947,  0.0217]]])

In [30]:
batch_weight = batch * unsqueezed_weights
batch_weight

tensor([[[[ 1.3006e-03, -2.4398e-01, -1.1518e-01,  5.0327e-02,  1.5864e-02],
          [-6.8409e-02, -9.8852e-02, -1.7278e-01, -2.3497e-01, -1.4825e-02],
          [-6.3869e-02,  1.6164e-01,  8.1192e-02,  4.4613e-01, -4.6576e-02],
          [-8.1952e-02,  6.1064e-02,  4.0561e-01, -2.4816e-01,  6.3587e-02],
          [-5.7634e-03, -1.4128e-01,  2.3899e-01, -1.9060e-02,  1.1050e-02]],

         [[-9.2071e-01,  7.0568e-01,  8.9178e-01, -1.0648e-01, -3.7171e-01],
          [ 6.8788e-02,  4.2287e-01, -2.6389e-01, -9.2218e-02, -3.9978e-01],
          [ 5.4535e-01, -4.8575e-01,  2.6425e-01,  8.2369e-01,  1.7065e+00],
          [-2.3468e-01,  6.5897e-01, -8.2683e-02,  7.6435e-01, -5.7999e-01],
          [-1.4987e-01, -1.3498e+00,  7.3041e-01, -1.7072e+00,  4.8542e-01]],

         [[-2.0099e-02,  1.2756e-02,  1.3676e-01, -4.1083e-03, -9.7949e-02],
          [-8.5945e-02,  5.7396e-02, -5.4333e-02,  1.0983e-01, -5.1761e-02],
          [-9.8844e-02,  5.4077e-02,  7.6038e-02, -6.3673e-02, -2.5101e-

In [31]:
img_gray_weighted = img_weight.sum(-3)
batch_gray_weighted = batch_weight.sum(-3)

batch_weight.shape, batch.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [ ]:
# Named tensors allow aligning dimensions automatically by name using align_as
img_named = img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch.refine_names(..., 'channels', 'rows', 'columns')
weights_named = torch.tensor([0.2126, 0.7152, 0.0722], names=('channels',))

# align_as adds dimensions of size 1 and permutes dimensions to match the target tensor
weights_aligned = weights_named.align_as(img_named)
print("weights_aligned shape:", weights_aligned.shape, "names:", weights_aligned.names)

# Now broadcasting works cleanly across named dimensions
gray_named = (img_named * weights_aligned).sum('channels')
print("gray_named shape:", gray_named.shape, "names:", gray_named.names)
